### ISSUE TITLE
Running tests without triggering a loadenv.restore() causes error

### ISSUE THREAD

**Issue by Myztiq** [Runnable/loadenv#7]
If I don't have this in the top of my test file my tests fail:

```
var loadenv = require('loadenv')
loadenv.restore()
loadenv({ project: 'link', debugName: 'link:test' })
```

If I instead use: 

```
loadenv = require('loadenv')({ project: 'link', debugName: 'link:test' })
```

it fails with the error:

```
/Users/myztiq/runnable/link/node_modules/loadenv/index.js:102
      if (val.match(/^\s*[+\-]?[0-9]+\s*$/)) {
             ^

TypeError: Cannot read property 'match' of null
    at /Users/myztiq/runnable/link/node_modules/loadenv/index.js:102:14
    at Object.<anonymous> (/Users/myztiq/runnable/link/node_modules/loadenv/node_modules/eson/lib/Parser.js:86:13)
    at Object.parse (native)
    at Parser.parse (/Users/myztiq/runnable/link/node_modules/loadenv/node_modules/eson/lib/Parser.js:81:15)
    at readDotEnvConfigs (/Users/myztiq/runnable/link/node_modules/loadenv/index.js:107:6)
    at Object.<anonymous> (/Users/myztiq/runnable/link/lib/models/navi-entry.js:8:101)
    at Module._compile (module.js:435:26)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/myztiq/runnable/link/node_modules/lab/lib/coverage.js:29:36)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/myztiq/runnable/link/test/unit/models/navi-entry.js:18:17)
    at Module._compile (module.js:435:26)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/myztiq/runnable/link/node_modules/lab/lib/coverage.js:34:28)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/myztiq/runnable/link/node_modules/lab/lib/cli.js:104:23
    at Array.forEach (native)
    at Object.internals.traverse (/Users/myztiq/runnable/link/node_modules/lab/lib/cli.js:100:19)
    at Object.exports.run (/Users/myztiq/runnable/link/node_modules/lab/lib/cli.js:49:29)
    at Object.<anonymous> (/Users/myztiq/runnable/link/node_modules/lab/bin/lab:3:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by rsandor** [comment]
So it looks like there is something process.env that has been unset (via a delete or set to null). Are you doing this in your tests?

**Comment by rsandor** [comment]
I'll put together a quick PR to handle this, FYI
